"""F15 — persistent per-level data as *shadow data modules* (§9.8).

The idea, and its dependency
----------------------------
LÖVE mounts the save directory **over** the game source, so a Lua source file placed
in the save directory shadows the same-pathed module inside `game.love`. That is spike
S2, and everything here is conditional on it: **if S2 fails, this module's effect is
inert** and F15 moves to tier 3 (bytecode patching).

Generation, not surgery
-----------------------
Where S2 holds, a persistent "this level starts with 9999 gold" needs no ZIP repack, no
in-place bytecode edit and no re-signing. It needs one generated file per level:

    <save dir>/kr1/data/levels/level01_data.lua     <- shadows the game's bytecode module

The generated module must be **additive**: it loads the shipped module (a bytecode copy
kept alongside, which we load with `love.filesystem.load`) and overrides only the fields
it targets. A game update therefore does not silently inherit stale values, and
`data revert` deletes two files and restores the shipped behaviour exactly.

Field names are unverified
--------------------------
Which keys a level-data table uses for starting gold and lives is *not* measured.
`all/systems.lua` carries `initial_gold` / `initial_lives` (§4.4) while the CLI surface
is specified with `starting_gold` / `starting_lives` (§10.6). Rather than guess, both
spellings are written: the extra key is inert if the game does not read it, and one of
them is right. This is reported as a note on every run, and the real answer comes from
spike S2 followed by `probe`.
"""

from __future__ import annotations

import datetime
import os
import re
from typing import Any, Dict, List, Optional

from krcheat.core import backup, lua_table as lt, mine, paths
from krcheat.core.errors import KrcheatError, NotFoundError, UsageError, ValidationError, milestone

#: Marks a file as ours, so `data revert --all` can find them without any state.
MARKER = "-- krcheat-f15"

#: Directive size cap. A shadow module is a few lines; anything larger is a bug.
MAX_MODULE_BYTES = 64 * 1024

#: `starting_gold` is the documented CLI name; `initial_gold` is what the shipped
#: constants suggest. Both are written (see the module docstring).
FIELD_ALIASES = {
    "starting_gold": ("initial_gold", "starting_gold"),
    "starting_lives": ("initial_lives", "starting_lives"),
    "gold": ("initial_gold", "starting_gold"),
    "lives": ("initial_lives", "starting_lives"),
}

WAVE_FIELD_ALIASES = {
    "gold": ("wave_gold", "gold"),
}

_OVERRIDES_BLOCK = re.compile(r"local OVERRIDES = (\{.*?\n\})", re.S)
_LEVEL_FIELD = re.compile(r"^-- krcheat-f15 level=(\d+)", re.M)

MODULE_TEMPLATE = """\
{mheader} level={level} generated={generated} version={version}
-- Generated by krcheat from the foundation document, section 9.8 (F15).
-- Do not edit: this file is regenerated whole. Remove it with 'krcheat data revert'.
--
-- It shadows {target} inside game.love and overrides only the fields
-- listed below. Requires spike S2 (save-directory require precedence) to have passed.
local OVERRIDES = {{
{table}}}
local base = {{}}
do
\tlocal loader = love and love.filesystem and love.filesystem.load
\tlocal chunk = loader and loader({original!r})
\tif chunk then
\t\tlocal ok, result = pcall(chunk)
\t\tif ok and type(result) == "table" then
\t\t\tbase = result
\t\tend
\tend
end
for key, value in pairs(OVERRIDES) do
\tbase[key] = value
end
return base
"""


def level_module_name(level):
    return "kr1/data/levels/level{0:02d}_data.lua".format(int(level))


def wave_module_name(level, mode):
    return "kr1/data/waves/level{0:02d}_waves_{1}.lua".format(int(level), mode)


def shadow_path(save_dir, module_name):
    return os.path.join(save_dir.path, *module_name.split("/"))


def original_path(save_dir, module_name):
    """Where the shipped bytecode copy lives, inside the save directory.

    It has to live under the save directory because that is the only place
    `love.filesystem.load` can reach without a `require` that would resolve back to
    the shadow itself.
    """
    return os.path.join(save_dir.path, "krcheat", "orig", module_name.replace("/", "__") + ".luac")


#: Where a shadow module can legitimately live. Discovery is deliberately confined to
#: these two directories rather than walking the whole save directory: a walk would also
#: find the *snapshot copies* under `~/.krcheat/backups` when the two trees overlap, and
#: report a reverted override as still installed.
SHADOW_DIRS = ("kr1/data/levels", "kr1/data/waves")


def _shadow_directories(save_dir):
    return [os.path.join(save_dir.path, *relative.split("/")) for relative in SHADOW_DIRS]


def find_installed(save_dir):
    """Every shadow module we installed, discovered by content, not by state."""
    found = []
    for directory in _shadow_directories(save_dir):
        try:
            names = sorted(os.listdir(directory))
        except OSError:
            continue
        for name in names:
            if not name.endswith(".lua"):
                continue
            full = os.path.join(directory, name)
            try:
                with open(full, "r", encoding="utf-8", errors="replace") as handle:
                    head = handle.read(4096)
            except OSError:
                continue
            if head.startswith(MARKER):
                found.append(read_installed(full, save_dir))
    found.sort(key=lambda item: (item.get("level") or 0, item.get("module") or ""))
    return found


def read_installed(path, save_dir=None):
    """Describe one installed shadow module by reading it back."""
    record = {"path": path, "module": None, "level": None, "fields": {}, "installed": None}
    try:
        with open(path, "r", encoding="utf-8") as handle:
            text = handle.read()
    except OSError:
        return record
    match = _LEVEL_FIELD.search(text)
    if match:
        record["level"] = int(match.group(1))
    first = text.splitlines()[0] if text else ""
    stamp = re.search(r"generated=([0-9T:+.-]+)", first)
    if stamp:
        record["installed"] = stamp.group(1)
    module = re.search(r"-- It shadows (\S+) inside game.love", text)
    if module:
        record["module"] = module.group(1)
    block = _OVERRIDES_BLOCK.search(text)
    if block:
        try:
            table = lt.parse("local obj1 = {0}\nreturn obj1\n".format(block.group(1)))
            record["fields"] = table.python()
        except lt.LuaTableError:
            record["fields"] = {}
    if save_dir is not None and record["module"]:
        record["original_copy"] = original_path(save_dir, record["module"])
    return record


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------


def render_module(level, target_module, overrides, original_rel, version_string=None):
    """Render the shadow module in the same style the save writer uses."""
    lines = []
    for key, value in overrides.items():
        lines.append('\t{0} = {1};'.format(lt.render_key(key), lt.render_scalar(value).text))
    body = "\n".join(lines)
    return MODULE_TEMPLATE.format(
        mheader=MARKER,
        level=int(level),
        generated=datetime.datetime.now().astimezone().isoformat(timespec="seconds"),
        version=version_string or "unknown",
        target=target_module,
        table=body + "\n" if body else "",
        original=original_rel,
    )


def expand_fields(field, value):
    """Map a documented field name onto the names the shipped code may use."""
    if field in FIELD_ALIASES:
        return {name: value for name in FIELD_ALIASES[field]}
    return {field: value}


def _extract_original(ctx, save_dir, module_name, result):
    """Copy the shipped module out of `game.love` so the shadow can call it."""
    archive = mine.Archive(ctx.bundle())
    if not archive.has(module_name):
        raise NotFoundError(
            "{0} is not in the archive; this level has no data module to override".format(
                module_name
            ),
            module=module_name,
        )
    data = archive.read(module_name)
    if not data:
        raise ValidationError("could not read {0} from the archive".format(module_name))
    if not data.startswith(b"\x1bLJ"):
        result.warn(
            "{0} is not LuaJIT bytecode (unexpected), it is copied as-is".format(module_name)
        )
    destination = original_path(save_dir, module_name)
    os.makedirs(os.path.dirname(destination), exist_ok=True)
    with open(destination, "wb") as handle:
        handle.write(data)
    ctx.log_info(
        "data.original_extracted",
        module=module_name,
        bytes=len(data),
        destination=destination,
    )
    return destination, data


def set_level_data(ctx, result, level, field, value, save_dir=None):
    """Generate or extend the shadow module for one level (§10.6)."""
    level = int(level)
    if level <= 0:
        raise UsageError("--level must be positive")
    value = int(value)
    if field not in FIELD_ALIASES and field not in ("initial_gold", "initial_lives",
                                                    "starting_gold", "starting_lives"):
        raise UsageError(
            "unknown level field {0!r}; expected starting_gold or starting_lives".format(field)
        )
    save_dir = save_dir or ctx.save_dir()
    module_name = level_module_name(level)
    target = shadow_path(save_dir, module_name)

    existing = read_installed(target, save_dir) if os.path.exists(target) else {"fields": {}}
    previous = dict(existing.get("fields") or {})
    overrides = dict(previous)
    overrides.update(expand_fields(field, value))
    for key in sorted(overrides):
        result.add_change(
            "{0}.{1}".format(module_name, key),
            previous.get(key),
            overrides[key],
        )

    original_rel = os.path.relpath(original_path(save_dir, module_name), save_dir.path)
    text = render_module(level, module_name, overrides, original_rel, _version_of(ctx))
    if len(text) > MAX_MODULE_BYTES:
        raise ValidationError("generated module exceeds {0} bytes".format(MAX_MODULE_BYTES))

    # Compile it in the game's own VM before it is installed (S8, D4). `run` mode is not
    # used: the module calls into LÖVE, which does not exist outside the game.
    from krcheat.core import safety as safety_mod

    if ctx.oracle:
        safety_mod.oracle_check(ctx, text, module_name, run=False)

    if ctx.dry_run:
        result.dry_run = True
        result.note("dry run: nothing was written")
        result.set(module=module_name, shadow=str(target), overrides=overrides)
        return result

    # Snapshot whatever exists. Adding a file is reversible by deleting it, so a
    # fresh install has nothing to preserve; overwriting an existing shadow does.
    files = [path for path in (target, original_path(save_dir, module_name)) if os.path.exists(path)]
    if files:
        manifest = backup.snapshot(
            files,
            label="data-set-level{0}".format(level),
            command=" ".join(ctx.argv) if ctx.argv else ctx.command,
            version_string=_version_of(ctx),
        )
        result.snapshot = manifest["id"]
        ctx.state.record_snapshot(manifest["id"])
        ctx.log_info("data.snapshot", snapshot=manifest["id"], files=len(files))
    else:
        result.note("no snapshot taken: neither the shadow nor its bytecode copy existed yet")

    _extract_original(ctx, save_dir, module_name, result)
    tmp = target + ".tmp"
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(tmp, "w", encoding="utf-8") as handle:
        handle.write(text)
    os.replace(tmp, target)
    ctx.log_info(
        "data.installed",
        module=module_name,
        shadow=target,
        bytes=len(text),
        overrides=overrides,
        sha256=paths.sha256_file(target),
    )
    result.set(module=module_name, shadow=str(target), overrides=overrides)
    result.note(
        "F15 requires spike S2 (save-directory require precedence). If S2 has not passed, this "
        "file is inert and the game ignores it."
    )
    if str(field).startswith("starting_"):
        result.note(
            "the level-data field name is unverified: both spellings suggested by the shipped "
            "code were written ({0})".format(", ".join(sorted(expand_fields(field, value))))
        )
    _record(ctx, result)
    return result


def set_wave_data(ctx, result, level, field, value, mode="campaign", save_dir=None):
    """Generate a shadow module for a level's wave data (§10.6).

    Refused rather than guessed: the wave reward table's shape is unverified, and a
    wrong key here would produce a file that changes nothing while reporting success.
    """
    raise milestone(
        "F15/waves",
        "wave-reward overrides are not implemented: the wave table's shape "
        "(kr1/data/waves/levelNN_waves_*.lua) has not been measured, and a wrong key would "
        "write a file that silently does nothing. Needs spike S2 plus a probe dump of one "
        "wave module. 'data set level <n> starting_gold|starting_lives <v>' is implemented.",
    )


def revert(ctx, result, level=None, save_dir=None):
    """Remove shadow modules for one level, or all of them (§10.6)."""
    save_dir = save_dir or ctx.save_dir()
    installed = find_installed(save_dir)
    if level is not None:
        installed = [item for item in installed if item.get("level") == int(level)]
    if not installed:
        result.note(
            "no shadow modules installed{0}".format(
                "" if level is None else " for level {0}".format(level)
            )
        )
        return result

    files = [item["path"] for item in installed]
    files += [item["original_copy"] for item in installed if item.get("original_copy") and os.path.exists(item["original_copy"])]
    if not ctx.dry_run:
        manifest = backup.snapshot(
            files,
            label="data-revert",
            command=" ".join(ctx.argv) if ctx.argv else ctx.command,
            version_string=_version_of(ctx),
        )
        result.snapshot = manifest["id"]
        ctx.state.record_snapshot(manifest["id"])
    for item in installed:
        for path in (item["path"], item.get("original_copy")):
            if not path or not os.path.exists(path):
                continue
            result.add_change(_rel(path, save_dir.path), "installed", None)
            if not ctx.dry_run:
                try:
                    os.remove(path)
                except OSError as exc:
                    raise ValidationError("cannot remove {0}: {1}".format(path, exc), path=path)
                _prune_empty_dirs(os.path.dirname(path), save_dir.path)
    if ctx.dry_run:
        result.dry_run = True
        result.note("dry run: nothing was removed")
    _record(ctx, result)
    result.note("shipped values are restored exactly: no game file was ever modified")
    return result


def list_overrides(ctx, save_dir=None, bundle=None):
    """Levels that *can* be overridden, and which overrides are installed."""
    save_dir = save_dir or ctx.save_dir()
    installed = find_installed(save_dir)
    installed_levels = sorted({item["level"] for item in installed if item.get("level")})
    candidates = []
    if bundle is None:
        try:
            bundle = ctx.bundle()
        except KrcheatError:
            bundle = None
    if bundle is not None:
        try:
            archive = mine.Archive(bundle)
            candidates = mine.mine_levels(archive)
        except Exception:
            candidates = []
    if not candidates:
        candidates = list(range(1, 27))
    return {
        "save_dir": save_dir.path,
        "levels": candidates,
        "installed": installed,
        "installed_levels": installed_levels,
    }


def _record(ctx, result):
    """Keep the machine-owned list of F15 files in step with the filesystem."""
    try:
        installed = find_installed(ctx.save_dir())
        ctx.state.put(
            "f15_installed",
            [
                {
                    "level": item.get("level"),
                    "module": item.get("module"),
                    "path": item.get("path"),
                    "fields": item.get("fields"),
                }
                for item in installed
            ],
        )
    except KrcheatError:
        pass


def _version_of(ctx):
    try:
        bundle = ctx.bundle()
        return bundle.expected_version_string()
    except KrcheatError:
        return None


def _rel(path, root):
    try:
        return os.path.relpath(path, root)
    except ValueError:
        return path


def _prune_empty_dirs(directory, stop):
    """Remove the directories we emptied, but never the save directory itself.

    Reverting an override should leave the save directory as it was found: an empty
    `kr1/data/levels/` is inert, but it looks like something was left behind.
    """
    stop = os.path.abspath(stop)
    current = os.path.abspath(directory)
    while current != stop and current.startswith(stop + os.sep):
        try:
            if os.listdir(current):
                return
            os.rmdir(current)
        except OSError:
            return
        current = os.path.dirname(current)
