"""Transport B — a generated bootstrap file (foundation §9.3, §16.1).

The mechanism
-------------
LÖVE mounts the save directory **over** the game source, so a Lua source file placed there
shadows the same-named module inside `game.love`. If that holds — it is spike S2, and it is
`data.py`'s premise too — then transport B is: **write one generated Lua file into the save
directory and change nothing else.** No ZIP repack, no pristine copy, no signature question,
and it is undone by deleting a file.

What that file replaces is `main_globals.lua`, chosen because it is the cheapest thing in the
archive to stand in for. Measured from the shipped bytecode:

* it is 119 bytes whose entire constant pool is `KR_PLATFORM = "mac"`, `KR_TARGET =
  "desktop"`, `KR_GAME = "kr1"`;
* `main.lua` really does load it by name — the string `main_globals` sits next to `require`
  and `pcall` in its constant pool.

So a replacement has an exact, testable contract: return those three constants, and add
nothing else to the namespace the game can see.

**Verified vs not.** The contract above is checked here, by compiling the generated module and
comparing its result to the shipped constants (when the game is installed). Whether the game
actually *prefers* the save directory's copy is not something this side can know: only the
game can answer that, so `install` writes the file and asks the game — see `verify()` — and
`available()` stays False until the game has said yes. That is the honest split, and it is why
there is an evidence file rather than an assumption.

The frame hook
--------------
Polling the channel needs a per-frame entry point, and `main_globals` is required early —
before the game has defined `love.update` or `love.draw`. So the bootstrap does not wrap a
function that does not exist yet; it installs a lazy wrapper that attaches to whichever of
`love.update` / `love.draw` / `love.run` appears first, and falls back to a `debug.sethook`
count hook if none of them ever does. Which one it got is written to the evidence file, because
"the channel works but only sometimes" is a symptom that needs a cause.
"""

from __future__ import annotations

import datetime
import os
import shutil

from krcheat.core import paths
from krcheat.core.errors import ChannelUnavailable, NotFoundError, UsageError
from krcheat.core.live.transport import LiveTransport

#: The file the game loads, and therefore the file we shadow.
SHADOW_MODULE = "main_globals.lua"

#: Marks a generated file as ours, so nothing depends on recorded state to find them.
MARKER = "-- krcheat-bootstrap"

#: Constants the shipped module defines. Asserted against the archive by `--self-test`-style
#: checks and by the tests, so a game update that adds a key is noticed rather than silently
#: dropped from the replacement.
EXPECTED_CONSTANTS = {
    "KR_PLATFORM": "mac",
    "KR_TARGET": "desktop",
    "KR_GAME": "kr1",
}

#: Evidence the game writes when our module is the one it loaded.
EVIDENCE_RELATIVE = os.path.join("krcheat", "bootstrap-evidence.json")

#: Where the shipped bytecode copy is kept, so the replacement can still hand the game the
#: real module if it wants it. Under the save directory, because that is the only place the
#: game's own loader can reach.
ORIGINAL_RELATIVE = os.path.join("krcheat", "orig", "main_globals.luac")

_STATE_KEY = "live.transport_b_verdict"

BOOTSTRAP_TEMPLATE = """\
{marker} generated={generated} version={version}
-- Generated by krcheat (foundation document 9.3, transport B). Do not edit.
-- It shadows {shadow} inside the game archive, returns the same constants, and
-- polls the live channel once per frame. Remove it with 'krcheat uninstall'.
--
-- The evidence file it writes is how 'krcheat install --check' finds out whether the
-- game really loaded this copy instead of the archived one. Without that, transport B
-- would be a guess (spike S2).

local krcheat = {{}}
krcheat.evidence = {evidence!r}
krcheat.original = {original!r}
krcheat.started = nil

local function write_evidence(how)
  local ok, fs = pcall(require, "love.filesystem")
  if not ok or type(fs) ~= "table" or not fs.write then return end
  pcall(fs.write, krcheat.evidence,
    '{{"loaded":true,"hook":"' .. tostring(how) .. '","version":"{version}"}}')
end

-- The channel poller. Kept deliberately small: it reads a file the CLI writes and runs
-- `loadstring` on it. Everything else lives on the Python side (section 11.5).
local function poll()
  local ok, fs = pcall(require, "love.filesystem")
  if not ok or not fs or not fs.read then return end
  local body = fs.read("krcheat/live-cmd.lua")
  if not body or body == "" or body == krcheat.last_cmd then return end
  krcheat.last_cmd = body
  local chunk, err = loadstring(body, "@krcheat-live")
  if not chunk then
    pcall(fs.write, "krcheat/live-out.txt", tostring(err))
    return
  end
  local ran, value = pcall(chunk)
  pcall(fs.write, "krcheat/live-out.txt", tostring(value))
end

-- Attach lazily: at this point the game has not defined love.update yet.
-- `_G` is indexed through pcall because this module is loaded very early, and a game (or a
-- test harness) where the globals table is not reachable yet must still get its constants
-- back rather than an error.
local function global_love()
  local ok, value = pcall(function() return _G.love end)
  if ok then return value end
  return nil
end

local function attach(name)
  local love_table = global_love()
  if type(love_table) ~= "table" then return false end
  local inner = love_table[name]
  if krcheat.hook or type(inner) ~= "function" then return false end
  love_table[name] = function(...)
    poll()
    return inner(...)
  end
  krcheat.hook = name
  write_evidence(name)
  return true
end

attach("update")
attach("draw")
if not krcheat.hook and type(debug) == "table" and debug.sethook then
  debug.sethook(poll, "", 200000)
  krcheat.hook = "debug.sethook"
  write_evidence("debug.sethook")
end

-- Give the game the module it asked for. The archived copy is loaded explicitly, because a
-- plain require would resolve straight back to this file.
local globals = {{ KR_PLATFORM = "mac", KR_TARGET = "desktop", KR_GAME = "kr1" }}
do
  local loader
  local ok, fs = pcall(require, "love.filesystem")
  if ok and fs then loader = fs.load end
  if loader then
    local chunk = loader(krcheat.original)
    if chunk then
      local ran, result = pcall(chunk)
      if ran and type(result) == "table" then
        for key, value in pairs(result) do globals[key] = value end
      end
    end
  end
end

if not krcheat.hook then write_evidence("none") end
return globals
"""


def shadow_path(save_dir):
    return os.path.join(save_dir.path, SHADOW_MODULE)


def original_path(save_dir):
    return os.path.join(save_dir.path, ORIGINAL_RELATIVE)


def evidence_path(save_dir):
    return os.path.join(save_dir.path, EVIDENCE_RELATIVE)


def render_bootstrap(version, save_dir):
    """The generated module. Pure: same inputs, same bytes."""
    return BOOTSTRAP_TEMPLATE.format(
        marker=MARKER,
        generated=datetime.datetime.now().strftime("%Y-%m-%d"),
        version=version,
        shadow=SHADOW_MODULE,
        evidence=EVIDENCE_RELATIVE.replace(os.sep, "/"),
        original=ORIGINAL_RELATIVE.replace(os.sep, "/"),
    )


def _is_ours(path):
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as handle:
            return handle.readline().startswith(MARKER)
    except OSError:
        return False


class PatchedLoveTransport(LiveTransport):
    name = "patched"
    description = "transport B (bootstrap module in the save directory)"
    requires = "spike S2: the game must load our file from the save directory"

    # -- availability --------------------------------------------------------

    def verdict(self):
        """What the game said about our bootstrap, or None if it has not been asked."""
        if self.ctx is None:
            return None
        return self.ctx.state.get(_STATE_KEY)

    def record_verdict(self, loaded, how=None, why=None):
        if self.ctx is None:
            return None
        verdict = {
            "loaded": bool(loaded),
            "hook": how,
            "why": why,
            "verified_at": datetime.datetime.now().isoformat(timespec="seconds"),
            "game": self.ctx.state.get("version_string"),
        }
        self.ctx.state.put(_STATE_KEY, verdict)
        return verdict

    def available(self):
        if not self.installed():
            return False, (
                "transport B is not installed. `krcheat install` writes one generated file "
                "into the save directory; the game must be launched once for it to take effect."
            )
        verdict = self.verdict()
        if not verdict:
            return False, (
                "transport B is installed but unverified: run the game once, then "
                "`krcheat install --check` (spike S2)."
            )
        if not verdict.get("loaded"):
            return False, (
                "the game did not load the bootstrap from the save directory, so S2 failed "
                "and transport B has to be the ZIP-repack variant instead ({0}).".format(
                    verdict.get("why") or "no reason recorded"
                )
            )
        return True, "verified by the game via {0}".format(verdict.get("hook") or "an unclear hook")

    # -- installation --------------------------------------------------------

    def save_dir(self):
        if self.ctx is None:
            return paths.find_save_dir()
        return self.ctx.save_dir()

    def installed(self):
        try:
            return _is_ours(shadow_path(self.save_dir()))
        except Exception:
            return False

    def archive_original(self):
        """The shipped bytecode, straight from the archive.

        Kept separate from writing it so the file mechanics can be tested somewhere the game
        is not installed — this is the only place in transport B that needs the archive at all.
        """
        from krcheat.core import mine

        with mine.Archive(self.bundle()) as archive:
            return archive.read(SHADOW_MODULE)

    def write_files(self, original_blob):
        """Write the replacement and the copy of the shipped module it hands back. Idempotent."""
        from krcheat import __version__

        if not original_blob:
            raise NotFoundError(
                "{0} is not in the game archive, so transport B has nothing to stand in for. "
                "The game may have been updated to a layout this version does not know.".format(
                    SHADOW_MODULE
                )
            )
        save_dir = self.save_dir()
        target = original_path(save_dir)
        os.makedirs(os.path.dirname(target), exist_ok=True)
        with open(target, "wb") as handle:
            handle.write(original_blob)

        text = render_bootstrap(__version__, save_dir)
        shadow = shadow_path(save_dir)
        with open(shadow, "w", encoding="utf-8") as handle:
            handle.write(text)
        self.log("bootstrap.installed", path=shadow, bytes=len(text))
        return {"shadow": shadow, "original": target, "bytes": len(text)}

    def install(self):
        """Fetch the shipped module and install the bootstrap around it."""
        save_dir = self.save_dir()
        if not save_dir.writable():
            raise ChannelUnavailable(
                "the save directory is not writable: {0}".format(save_dir.path)
            )
        # The archived copy comes first: without it the replacement cannot hand the game the
        # real module, and a half-finished install is worse than none.
        return self.write_files(self.archive_original())

    def uninstall(self):
        """Remove everything we wrote. Returns the paths that are now gone."""
        save_dir = self.save_dir()
        removed = []
        shadow = shadow_path(save_dir)
        if _is_ours(shadow):
            os.remove(shadow)
            removed.append(shadow)
        elif os.path.exists(shadow):
            raise UsageError(
                "{0} exists but was not generated by krcheat, so it was left alone. Move it "
                "aside yourself if you want transport B installed.".format(shadow)
            )
        own_dir = os.path.join(save_dir.path, "krcheat")
        for relative in (ORIGINAL_RELATIVE, EVIDENCE_RELATIVE):
            path = os.path.join(save_dir.path, relative)
            if os.path.exists(path):
                os.remove(path)
                removed.append(path)
        # Only remove directories we own, and only if they are empty: the evidence file and
        # the original copy are the only things krcheat puts there.
        for directory in (
            os.path.dirname(original_path(save_dir)),
            own_dir,
        ):
            try:
                os.rmdir(directory)
            except OSError:
                pass
        if self.ctx is not None:
            self.ctx.state.drop(_STATE_KEY)
        self.log("bootstrap.removed", count=len(removed))
        return removed

    def repair(self):
        """Re-write the bootstrap after a Steam integrity check or a game update."""
        if not self.installed():
            return None
        return self.install()

    def read_evidence(self):
        """What the game wrote, if it ever ran our module."""
        path = evidence_path(self.save_dir())
        try:
            with open(path, "r", encoding="utf-8", errors="replace") as handle:
                return handle.read()
        except OSError:
            return None

    def _game_wrote_since(self, when):
        """Did the game itself run since `when`?

        The evidence file is written by our bootstrap, so its presence proves success — but its
        *absence* proves nothing on its own: the game may simply not have been started yet.
        Distinguishing those two cases is what keeps `--check` from declaring S2 a failure
        every time it is run too early.

        The discriminator is that the game writes its own files (`settings.lua`, slots) when it
        runs. If any of those is newer than the install, the game ran and did not load us.
        """
        save_dir = self.save_dir()
        ours = {"main_globals.lua", "krcheat"}
        newest = 0.0
        try:
            names = os.listdir(save_dir.path)
        except OSError:
            return False
        for name in names:
            if name in ours:
                continue
            try:
                newest = max(newest, os.path.getmtime(os.path.join(save_dir.path, name)))
            except OSError:
                continue
        return newest > float(when or 0.0)

    def installed_at(self):
        try:
            return os.path.getmtime(shadow_path(self.save_dir()))
        except OSError:
            return None

    def check(self):
        """Ask the evidence file what happened. Records the verdict in the state cache."""
        import json as json_mod

        raw = self.read_evidence()
        if not raw:
            installed_at = self.installed_at()
            if self._game_wrote_since(installed_at):
                why = (
                    "the game ran after installation and did not write the evidence file, so it "
                    "did not load this copy: save-directory require precedence does not hold "
                    "for this build"
                )
                self.record_verdict(False, why=why)
                return {"loaded": False, "reason": why, "conclusive": True}
            reason = "the game has not been started since the bootstrap was installed"
            return {
                "loaded": False,
                "reason": reason,
                "conclusive": False,
                "hint": "launch the game once — from Steam is fine — and run this again",
            }
        try:
            payload = json_mod.loads(raw)
        except ValueError:
            self.record_verdict(False, why="the evidence file is not valid JSON")
            return {
                "loaded": False,
                "reason": "the evidence file is not valid JSON",
                "raw": raw,
                "conclusive": True,
            }
        payload["conclusive"] = True
        self.record_verdict(payload.get("loaded"), how=payload.get("hook"))
        return payload

    def bundle(self):
        if self.ctx is None:
            return paths.find_app_bundle()
        return self.ctx.bundle()

    # -- the interface -------------------------------------------------------

    def start(self, launch=True, args=None):
        usable, why = self.available()
        if not usable:
            raise ChannelUnavailable(why)
        raise ChannelUnavailable(
            "transport B's bootstrap is verified, but driving a live session through it is not "
            "implemented in this build: the request/response files are written by the "
            "bootstrap, and only the dylib reader in transport A is wired up. Use `krcheat "
            "play --transport dylib`."
        )

    def stop(self, quit_game=False):
        return None

